# Generated by Django 5.0.6 on 2024-06-20 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='monthly_contribution',
            new_name='expected_monthly_contribution',
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_manager.client')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('investment_type', models.CharField(choices=[('fd', 'Fixed Deposit'), ('bond', 'Government Bond'), ('t_bill', 'Treasury Bill'), ('abc_bf', 'ABC Balanced Fund'), ('abc_ef', 'ABC Equity Fund'), ('abc_mmf', 'ABC Money Market Fund'), ('abc_usdf', 'ABC USD Fund'), ('abc_usd_hyf', 'ABC USD High-Yield Fund'), ('abc_zmw_hyf', 'ABC ZMW High-Yield Fund'), ('mpile_bf', 'Mpile Balanced Fund'), ('mpile_gf', 'Mpile Gratuity Fund'), ('mpile_hydf', 'Mpile High-Yield Debt Fund'), ('mpile_lef', 'Mpile Local Equity Fund'), ('mpile_mmf', 'Mpile Money Market Fund'), ('mpile_osef', 'Mpile Offshore Equity Fund'), ('mpile_pf', 'Mpile Property Fund')], max_length=50)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_annual_growth_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('expected_current_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_manager.client')),
            ],
        ),
    ]
