# Generated by Django 5.0.6 on 2024-06-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0002_rename_monthly_contribution_client_expected_monthly_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='investment_duration',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='client',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='start_date',
            field=models.DateField(),
        ),
    ]
