# Generated by Django 5.0.6 on 2024-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0004_client_city_client_created_at_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='investment_duration',
            field=models.IntegerField(),
        ),
    ]
