# Generated by Django 5.0.6 on 2024-06-23 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0005_alter_client_investment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_nrc',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='NRC must be in the format 123456/78/9', regex='^\\d{6}/\\d{2}/\\d$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
