# Generated by Django 5.0.6 on 2024-06-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0006_alter_client_client_nrc_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_duration',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
