# Generated by Django 5.0.6 on 2024-06-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0007_investment_investment_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='start_date',
            new_name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='client',
            name='investment_duration',
        ),
        migrations.RemoveField(
            model_name='client',
            name='maturity_date',
        ),
    ]
