# Generated by Django 5.0.6 on 2024-06-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0008_rename_start_date_client_date_of_joining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='investment_type',
            new_name='contribution_type',
        ),
        migrations.AddField(
            model_name='client',
            name='contribution_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=50),
            preserve_default=False,
        ),
    ]
