# Generated by Django 5.0.6 on 2024-06-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0010_alter_investment_expected_current_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='expected_current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
