# Generated by Django 5.0.6 on 2024-06-24 03:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0011_alter_investment_expected_current_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='expected_monthly_contribution',
            new_name='expected_contribution',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='expected_annual_growth_rate',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contribution_amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='fee_rate_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('3.000'), max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='investable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('ddacc', 'DDACC'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='bank_transfer', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_annual_growth_rate_percentage',
            field=models.DecimalField(decimal_places=3, default=15.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='contribution_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annual'), ('annual', 'Annual'), ('once_off', 'Once-Off')], max_length=50),
        ),
    ]
