# Generated by Django 5.0.6 on 2024-06-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0012_rename_expected_monthly_contribution_client_expected_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='investable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
