# Generated by Django 5.0.6 on 2024-06-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager', '0014_investment_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='manager',
        ),
    ]
